export const APPOINTMENT_STATUS = 
{
    ATTENDED: 'ATTENDED',
    CANCELLED: 'CANCELLED',
    DRAFT: 'DRAFT',
    SCHEDULED: 'SCHEDULED'
};

export const AUTHENTICATION_FORM = 
{
    LOG_IN: 'LOG_IN',
    REGISTRATION: 'REGISTRATION'
};

export const USER_TYPE = 
{
    ADMIN: 'ADMIN',
    DOCTOR: 'DOCTOR',
    PATIENT: 'PATIENT'
};